# -*- coding: utf-8 -*-
"""PCA_example_DONE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KVW-LGVkPQksLM5C-9BCilcD8S9uAHb_

# **ANALIZA SKŁADOWYCH GŁÓWNYCH**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""Pobranie danych:"""

data=pd.read_csv('PCA_simpledata.csv')
data

"""Wykres rozrzutu:"""

plt.scatter(data.iloc[:,0],data.iloc[:,1])

"""Macierz korelacji:"""

CorrMatrix = np.array(data.corr())
CorrMatrix

"""Wartości i wektory własne macierzy korelacji:"""

#TODO
w, v = np.linalg.eig(CorrMatrix)
print(w)
print(v)

v[:,0]

v[:,1]

"""Sprawdź poprawność wyliczeń wektorów i wartości własnych. Wykorzystaj równanie na wartości własne."""

#TODO
u=v[:,1]
print(u)

lam = w[1]
print(lam)

print(np.dot(CorrMatrix,u))

print(lam*u)

"""Dane w nowym układzie współrzędnych wyznaczonym przez wektory własne macierzy korelacji (**zobacz slajdy 30 i 31 z ED_teoria_4.pdf**):

"""

#TODO
#print(data.iloc[0,0]*v[0,0]+data.iloc[0,1]*v[1,0],data.iloc[0,0]*v[0,1]+data.iloc[0,1]*v[1,1])
T=np.array([])
for i in range (10):
 x=data.iloc[i,0]*v[0,0]+data.iloc[i,1]*v[1,0]
 y=data.iloc[i,0]*v[0,1]+data.iloc[i,1]*v[1,1]
 T=np.append(T,[x,y],axis=0)
 print(x,y)
 #print(data.iloc[i,0]*v[0,0]+data.iloc[i,1]*v[1,0],data.iloc[i,0]*v[0,1]+data.iloc[i,1]*v[1,1])

T=np.reshape(T,(10,2))



"""Wykres rozrzutu danych w nowym układzie:"""

np.info(T)

#TODO
plt.scatter(T[:,0],T[:,1])
plt.show()

