# -*- coding: utf-8 -*-
"""ED_7_kNN_zadanie_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oElyxq41hZjdEXbFnuXrpEI3ujYJYJBT
"""

import pandas as pd
import numpy as np
import random
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

from sklearn.neighbors import KNeighborsClassifier

dataFile = pd.read_csv('car.data')

dataFile.head()

dataFile.info()

buying =  list(dataFile["buying"])
maint  =  list(dataFile["maint"])
doors  =  list(dataFile["doors"])
persons =  list(dataFile["persons"])
lug_boot =   list(dataFile["lug_boot"])
safety =  list(dataFile["safety"])
car_class =   list(dataFile["class"])

buying_encoded=le.fit_transform(buying)
maint_encoded=le.fit_transform(maint)
doors_encoded=le.fit_transform(doors)
persons_encoded=le.fit_transform(persons)
lug_boot_encoded=le.fit_transform(lug_boot)
safety_encoded=le.fit_transform(safety)
car_class_encoded=le.fit_transform(car_class)

data=list(zip(buying_encoded,maint_encoded,doors_encoded,persons_encoded,lug_boot_encoded,safety_encoded))
print(data)

label=le.fit_transform(car_class_encoded)
print(label)

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(data, label, test_size=1382)

for i in range (3,150):
  neigh = KNeighborsClassifier(n_neighbors=i,p=2)
  neigh.fit(x_train,y_train)
  neigh.score(x_test,y_test)
  print(i, " " ,neigh.score(x_test,y_test))

